'use strict';
const width = 10;
const height = 10;
let area = 0;
area = width * height;
console.log('The area is: ', area);
console.log('The type of area is: ', typeof area);
const bill = 300;
const payment = 500;
let change = 0;
change = payment - bill;
console.log('The Change is: $', change);
console.log('The type of change is: ', typeof change);
const quizzes = 100;
const midterm = 90;
const final = 85;
let grade = 0;
grade = (quizzes * midterm * final) / 3;
console.log('The grade is: ', grade);
console.log('The type of grade is: ', typeof grade);
const firstName = 'Samuel';
const lastName = 'Castaneda';
let fullName = '';
fullName = firstName + ' ' + lastName;
console.log('Value of fullName: ', fullName);
console.log('Type of fullName: ', typeof fullName);
const ph = 6;
let isAcidic = false;
isAcidic = ph < 7;
console.log('The Value of isAcidic: ', isAcidic);
console.log('The type of isAcidic is: ', typeof isAcidic);
const headCount = 400;
let isSparta = true;
isSparta = headCount === 300;
console.log('The value of isSparta: ', isSparta);
console.log('The type of for isSparta: ', typeof isSparta);
let motto = '';
motto = fullName + ' is the GOAT';
console.log('The value of motto: ', motto);
console.log('The type of for motto: ', typeof motto);
